---
name: Checks

on:
  pull_request:
    branches:
      - main

jobs:
  original-black:
    name: Original black check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608  # 4.1.0
      - name: Black
        uses: psf/black@e87737140f32d3cd7c44ede75f02dcd58e55820e  # 23.9.1

  modified-black:
    name: Modified black check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608  # 4.1.0

      # The following steps should be part of a composite action
      - name: Setup Python
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236  # 4.7.1
        with:
          python-version: '3.10'
      
      - name: Setup Black
        run: python -m pip install black==23.9.1
      
      - name: Execute Black
        run: |
          black_output=$(black --diff .)

          # construct the job summary
          echo "Black output:" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`python" >> $GITHUB_STEP_SUMMARY
          echo "${black_output}" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
